s = "Tops Technologiese"

print(len(s))
print(s)
print(s.capitalize())
print(s.lower())
print(s.upper())
print(s.swapcase())
print("react programing".title())
print(s.center(40, "*"))
print(s.count("T"))
print(s.endswith("ese"))
print(s.startswith("To"))
print(s.find("log"))
print(s.index("T",2))
print("tops123".isalnum())
print("123".isalnum())
print("tops 123".isalnum())
print("123".isnumeric())
print(" ".isspace())
print(s.istitle())
print("TOPS".isupper())
print("tops".islower())
print("Hello".replace("l","w"))